export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const LOAD_GROUP_SUCCESS = "LOAD_GROUP_SUCCESS";
export const LOAD_GROUP_COMMENTS_SUCCESS = "LOAD_GROUP_COMMENTS_SUCCESS";

export const LOAD_SAVED_GROUP_SUCCESS = "LOAD_SAVED_GROUP_SUCCESS";
